### ISSUE TITLE
[configure][profile][default-profile] - Setting profile name with spaces will silently break the default profile functionality

### ISSUE THREAD

**Issue by aminalali8** [bunnyshell/cli#4]
Creating a profile with a space in the name seems to fail the default profile functionality. 
Trying to identify issue source code.

**Comment by BunnyCrlu** [comment]
Hey @aminalali8 we're aware there are some quirks when using Uppercase in the profile name, I'll check today if the same applies for spaces (I'd assume it does)

We'll take this into consideration after the next release.
